version: "3"

networks:
  developer:
    external: true

volumes:
  postgres-11:

services:
  postgres-11:
    image: postgres:11-alpine
    container_name: postgres-11
    ports:
      - "10011:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-11:/var/lib/postgresql/data
    networks:
      - developer
