version: "3"

networks:
  developer:
    external: true

volumes:
  mysql-5:

services:
  mysql-5:
    image: mysql:5.7-debian
    container_name: mysql-5
    ports:
      - 10205:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    volumes:
      - mysql-5:/var/lib/mysql
    networks:
      - developer
