version: "3"

networks:
  developer:
    external: true

volumes:
  mysql-8:

services:
  mysql-8:
    image: mysql:8.0-debian
    container_name: mysql-8
    ports:
      - 10208:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    volumes:
      - mysql-8:/var/lib/mysql
    networks:
      - developer
